name: feature-workflow

on:
  push:
    branches:
      - feat/**
      - fix/**
      - chore/**
      - task/**

permissions:
  pull-requests: write
  contents: write
  repository-projects: write

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/setup-node-yarn

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/setup-node-yarn

      - name: Run lint
        run: |
          cd app
          yarn lint
          yarn tsc --noEmit

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/setup-node-yarn

      - name: Build application
        run: |
          cd app
          yarn build
